punch/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

from punch.main import views as main_views
from punch.monitor import views as monitor_views


urlpatterns = patterns(
    '',
    # My URLS here
    url(r'^$', main_views.HomeView.as_view()),
    url(r'^signup$', main_views.RegisterView.as_view()),
    url(r'^login$', main_views.LoginView.as_view()),
    url(r'^logout$', main_views.LogoutView.as_view()),
    url(r'^dashboard$', main_views.DashboardView.as_view()),
    # Monitoring URLs
    url(r'^location/create$', monitor_views.LocationCreateView.as_view()),
    url(r'^location/(?P<pk>\d+)/$', monitor_views.LocationView.as_view(), name='location-detail'),
    url(r'^location/(?P<pk>\d+)/edit$', monitor_views.LocationEditView.as_view(), name='location-edit'),
    url(r'^location/(?P<l_pk>\d+)/bridge/add$', monitor_views.BridgeCreateView.as_view(), name='bridge-create'),
    url(r'^location/(?P<l_pk>\d+)/tank/add$', monitor_views.TankCreateView.as_view(), name='tank-create'),
    url(r'^location/(?P<l_pk>\d+)/tank/(?P<pk>\d+)/$', monitor_views.TankView.as_view(), name='tank-create'),
    url(r'^location/(?P<l_pk>\d+)/tank/(?P<pk>\d+)/end$', monitor_views.TankFinishRedirectView.as_view(), name='tank-finish'),
    # Update entry point
    url(r'^updater$', csrf_exempt(monitor_views.BridgeEntryView.as_view()), name='reading-entry-point'),
    url(r'^heartbeat$', csrf_exempt(monitor_views.HeartBeatEntryView.as_view()), name='heartbeat'),
    url(r'^admin/', include(admin.site.urls)),
)

punch/monitor/models.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models


class Location(models.Model):
    """Model for describing a location which contains a bunch of sensors."""
    name = models.CharField(max_length=80)

    # For more details about many-to-many relationships in Django:
    # https://docs.djangoproject.com/en/dev/topics/db/examples/many_to_many/
    users = models.ManyToManyField(User)

    def get_absolute_url(self):
        return '/location/{id}/'.format(id=self.id)

    def __repr__(self):
        return '<Location: {name}>'.format(name=self.name)

    def __str__(self):
        return '<{name}>'.format(name=self.name)


class Bridge(models.Model):
    """Model that identifies a central hub."""
    # TODO: Figure out what this length should be
    uuid = models.CharField(max_length=32, unique=True)

    # For more details about many-to-one relationships in Django:
    # https://docs.djangoproject.com/en/1.7/topics/db/examples/many_to_one/
    location = models.ForeignKey(Location)

    def get_absolute_url(self):
        return self.location.get_absolute_url()


class Tank(models.Model):
    """Model that contains the fermentation tank abstraction."""
    # TODO: Figure out if this is the correct length for 128-bit hex identifier
    sensor_uuid = models.CharField(max_length=32)
    name = models.CharField(max_length=80)

    # Start/End date stuff
    # Automatically add the start date when the object is first created
    started_at = models.DateTimeField(auto_now_add=True)
    ended_at = models.DateTimeField(blank=True, null=True)

    # For UI Placement
    y = models.IntegerField(blank=True, null=True)
    x = models.IntegerField(blank=True, null=True)

    # Relationships
    location = models.ForeignKey(Location)

    # Alert settings
    alert_temp_high = models.FloatField(blank=True, null=True)
    alert_temp_low = models.FloatField(blank=True, null=True)
    alert_brix_high = models.FloatField(blank=True, null=True)
    alert_brix_low = models.FloatField(blank=True, null=True)

    @property
    def is_active(self):
        """Return a boolean indicating if the tank is currently active."""
        return self.ended_at is None

    def deactivate(self):
        """Deactivate this tank."""
        if self.is_active:
            self.ended_at = datetime.utcnow()

    @property
    def total_days(self):
        """Return the number of days that the tank was active for."""
        if self.is_active:
            dt = datetime.utcnow().replace(tzinfo=None) - self.started_at.replace(tzinfo=None)
        else:
            dt = self.ended_at.replace(tzinfo=None) - self.started_at.replace(tzinfo=None)
        return dt.days + 1

    def get_absolute_url(self):
        return self.location.get_absolute_url() + 'tank/{id}/'.format(id=self.id)


class Reading(models.Model):
    """Model that contains each readings for a particular tank."""
    # Relationships
    tank = models.ForeignKey(Tank)

    # Metrics
    temperature = models.FloatField()
    brix = models.FloatField()

    # Time of reading
    created_at = models.DateTimeField(auto_now_add=True)

punch/main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import EmailValidator

from punch.main.models import UserProfile


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': "A user with that username already exists.",
        'password_mismatch': "The two password fields didn't match.",
    }

    username = forms.CharField(label="Email address", max_length=30, validators=[EmailValidator])

    password1 = forms.CharField(label="Password",
        widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm password",
        widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification.")

    phone_number = forms.CharField(label="Phone number", max_length=17, validators=[UserProfile.phone_regex])

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        # The email and the username should be the same
        user.email = user.username

        # Force the save, disregard the commit flag
        user.save()

        # Hook it up to a user profile
        user_profile = UserProfile(user=user, phone_number=self.cleaned_data["phone_number"])
        user_profile.save()

        return user

punch/monitor/forms.py
from django import forms

from punch.monitor.models import Tank, Bridge


class TankCreationForm(forms.ModelForm):
    """
    A form for creating a new tank. This form ensures that no new tanks are added that have a sensor ID that is also
    active for another tank.
    """
    error_messages = {
        'duplicate_sensor': "An active tank has already registered this sensor.",
    }

    name = forms.CharField(label="Name", max_length=80)
    sensor_uuid = forms.CharField(label="Sensor UUID", max_length=32)
    alert_temp_high = forms.FloatField(label="Highest temperature that triggers alert", required=False)
    alert_temp_low = forms.FloatField(label="Low temperature that triggers alert", required=False)

    class Meta:
        model = Tank
        fields = ("sensor_uuid", "name", "alert_temp_high", "alert_temp_low")

    def clean_sensor_uuid(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        sensor_uuid = self.cleaned_data["sensor_uuid"]
        try:
            Tank.objects.get(sensor_uuid=sensor_uuid, ended_at=None)
        except Tank.DoesNotExist:
            return sensor_uuid
        raise forms.ValidationError(
            self.error_messages['duplicate_sensor'],
            code='duplicate_sensor_uuid',
        )


class BridgeCreationForm(forms.ModelForm):
    """
    A form for adding a new bridge.
    """
    uuid = forms.CharField(label="Bridge UUID", max_length=32)

    class Meta:
        model = Bridge
        fields = ('uuid',)

    def clean_uuid(self):
        """Clean the uuid for unnecessary hyphens."""
        return self.cleaned_data["uuid"].replace('-', '')

punch/main/views.py
from django.views.generic import TemplateView, FormView, RedirectView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from punch.main.forms import UserCreationForm
from punch.mixins import LoginRequiredMixin


class HomeView(TemplateView):
    template_name = 'home.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class DashboardView(LoginRequiredMixin, RedirectView):
    template_name = 'dashboard.html'

    def get_redirect_url(self, *args, **kwargs):
        locations = self.request.user.location_set.all()
        if locations:
            return locations[0].get_absolute_url()
        else:
            return '/location/create'


class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = UserCreationForm
    success_url = '/dashboard'

    def form_valid(self, form):
        result = super(RegisterView, self).form_valid(form)

        # Login the user automatically after user is created
        user = authenticate(
            username=self.request.POST.get('username'),
            password=self.request.POST.get('password1')
        )
        login(self.request, user)

        return result


class LoginView(FormView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    success_url = '/dashboard'

    def form_valid(self, form):
        login(self.request, form.get_user())
        next_url = self.request.POST.get("next", self.success_url)
        return redirect(next_url)


class LogoutView(RedirectView):
    url = '/login'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

punch/monitor/views.py
import json
from datetime import datetime, timedelta
from random import random

from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import DetailView, RedirectView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from punch.monitor.lib.raw_bridge import RawBridge
from punch.monitor.models import (
    Location,
    Bridge,
    Tank,
    Reading,
)
from punch.monitor.forms import TankCreationForm, BridgeCreationForm
from punch.monitor.signals import check_and_send_alerts
from punch.mixins import LoginRequiredMixin


# TODO: permissions based on location ownership
# https://docs.djangoproject.com/en/1.7/topics/class-based-views/mixins/

# Good reference forms in general:
# https://docs.djangoproject.com/en/1.7/topics/class-based-views/generic-display/
# https://docs.djangoproject.com/en/1.7/topics/class-based-views/generic-editing/


class LocationCreateView(LoginRequiredMixin, CreateView):
    model = Location
    fields = ('name', 'users')


class LocationEditView(LoginRequiredMixin, UpdateView):
    model = Location


class LocationDeleteView(LoginRequiredMixin, DeleteView):
    model = Location


class LocationView(LoginRequiredMixin, DetailView):
    model = Location

    def get_context_data(self, **kwargs):
        context = super(LocationView, self).get_context_data(**kwargs)
        context['active_tanks'] = [tank for tank in self.object.tank_set.all() if tank.is_active]
        context['finished_tanks'] = [tank for tank in self.object.tank_set.all() if not tank.is_active]
        return context

    def dispatch(self, request, *args, **kwargs):
        location = get_object_or_404(Location, pk=kwargs['pk'])
        if location and not location.bridge_set.all():
            return redirect(location.get_absolute_url() + 'bridge/add')
        return super(LocationView, self).dispatch(request, *args, **kwargs)


class BridgeCreateView(LoginRequiredMixin, CreateView):
    model = Bridge
    fields = ('uuid', )
    form_class = BridgeCreationForm

    def get_context_data(self, **kwargs):
        context = super(BridgeCreateView, self).get_context_data(**kwargs)
        location = Location.objects.get(pk=int(self.kwargs.get('l_pk')))
        context['location'] = location
        context['needs_bridge'] = 1 - len(location.bridge_set.all())
        return context

    def form_valid(self, form):
        location = Location.objects.get(pk=self.kwargs.get('l_pk'))
        form.instance.location = location
        return super(BridgeCreateView, self).form_valid(form)


class BridgeDeleteView(LoginRequiredMixin, DeleteView):
    model = Bridge


class TankCreateView(LoginRequiredMixin, CreateView):
    model = Tank
    form_class = TankCreationForm
    fields = ('sensor_uuid', 'name')

    def get_context_data(self, **kwargs):
        context = super(TankCreateView, self).get_context_data(**kwargs)
        location = Location.objects.get(pk=int(self.kwargs.get('l_pk')))
        context['location'] = location
        context['sensor_uuids'] = self.get_sensor_uuids(location)
        return context

    def form_valid(self, form):
        location = Location.objects.get(pk=self.kwargs.get('l_pk'))
        form.instance.location = location
        self.remove_sensor_uuid(location, form.instance.sensor_uuid)
        return super(TankCreateView, self).form_valid(form)

    def get_sensor_uuids(self, location):
        sensor_uuids = []
        for bridge in location.bridge_set.all():
            b = RawBridge(bridge.uuid)
            sensor_uuids.extend(list(b.get_available_sensors()))
        return sensor_uuids

    def remove_sensor_uuid(self, location, sensor_uuid):
        for bridge in location.bridge_set.all():
            b = RawBridge(bridge.uuid)
            b.remove_available_sensor(sensor_uuid)


class TankEditView(LoginRequiredMixin, UpdateView):
    model = Tank


class TankDeleteView(LoginRequiredMixin, DeleteView):
    model = Tank


class TankView(LoginRequiredMixin, DetailView):
    model = Tank

    def get_context_data(self, **kwargs):
        context = super(TankView, self).get_context_data(**kwargs)
        location = Location.objects.get(pk=int(self.kwargs.get('l_pk')))
        context['location'] = location

        readings = self.object.reading_set.all()
        if readings:
            context['readings'] = serializers.serialize('json', readings)
        else:
            # If no readings, use randomly generated data
            context['readings'] = serializers.serialize('json', self.create_fake_readings())
        return context

    # TODO: remove when we have real readings
    def create_fake_readings(self):
        readings = []
        for i in range(0, 100):
            t = random() * 8 + 27
            b = random() * 2 + 30 - 1.02 ** i - i * 0.2
            d = datetime(2014, 11, 24, 18, 12, 8, 393455) + timedelta(minutes=120 * i)
            readings.append(Reading(temperature=t, brix=b, created_at=d))
        return readings


class TankFinishRedirectView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        tank = get_object_or_404(Tank, pk=kwargs['pk'])
        tank.deactivate()
        tank.save()
        return tank.get_absolute_url()


class BridgeEntryView(View):

    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body)
            self.process_load(data)
        except ValueError:
            pass
        return HttpResponse(
            json.dumps({'received': True}),
            content_type='application/json',
            **kwargs
        )

    def process_load(self, data):
        bridge_uuid = str(data['bridge_uuid'].replace('-', ''))
        sensor_uuid = str(data['sensor_uuid'])
        temperature = float(data['temperature'])
        brix = float(data['brix'])
        try:
            tank = Tank.objects.get(sensor_uuid=sensor_uuid, ended_at=None)
            # If tank exists, add a new reading
            reading = Reading(temperature=temperature, brix=brix, tank=tank)
            # TODO: add signal for reading
            reading.save()
            check_and_send_alerts(reading)
        except Tank.DoesNotExist:
            # Otherwise, tank doesn't exist and should be noticed by the set.
            r_bridge = RawBridge(bridge_uuid)
            r_bridge.add_available_sensor(sensor_uuid)


class HeartBeatEntryView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse(
            json.dumps({'received': True}),
            content_type='application/json',
            **kwargs
        )

punch/templates/monitor/bridge_form.html
{% extends "dash_base.html" %}
{% load staticfiles %}
{% load addcss %}
{% block title %}Add a new bridge{% endblock %}
{% block nav_title %}Add bridge{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
    {% if not needs_bridge %}
    <nav>
      <ul class="pager">
        <li class="previous"><a href="{{ location.get_absolute_url }}"><span aria-hidden="true">&larr;</span> Back to location page</a></li>
      </ul>
    </nav>
    {% endif %}

    {% if needs_bridge %}
        <h1>{{ location.name }} <span class="gray">is almost set!</span></h1>
        <p>
            Before we can get your location up and running, we'll need to hook up a bridge device to this particular
            location.
        </p>

    {% endif %}

    <h3>What's a bridge?</h3>
    <p>
        We need to communicate to each sensor in the tank through the a device called a bridge. Our sensor devices are ultra-low
        powered so that they can continuously keep monitoring your batches of wine. That means they don't have enough power to reach the
        Internet on their own.

        The bridge relays all the sensor readings to our servers.
    </p>

    <h3>Add a bridge to <span class="gray">{{ location.name }}</span></h3>
    <form method="POST">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="col-sm-7 alert alert-warning" role="alert">
              <span class="sr-only">Error:</span>
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        {% if form.uuid.errors %}
        <div class="row">
            <div class="col-sm-7 alert alert-danger" role="alert">
              <span class="sr-only">Error:</span>
              {{ form.uuid.errors }}
            </div>
        </div>
        {% endif %}

        <div id="uuid-group" class="form-group">
           <div class="row">
               <label for="id_uuid" class="col-sm-2 control-label">{{ form.uuid.label }}</label>
               <div class="col-sm-4">
                   {{ form.uuid | addcss:"form-control"}}
               </div>
           </div>
        </div>
        <button type="submit" class="btn btn-large btn-primary">Add</button>
    </form>
{% endblock %}


{% block js %}
    <script>
    $(document).ready(function(){
        $('#id_uuid').keypress(function (e) {
            console.log(e.currentTarget.value.length);
            var regex = new RegExp("^[a-zA-Z0-9]+$");
            var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
            if (e.currentTarget.value.length === 32) {
                $('#uuid-group').addClass('has-success');
            } else {
                $('#uuid-group').removeClass('has-success');
            }
            if (regex.test(str)) {
                return true;
            }

            e.preventDefault();
            return false;
        });
    });
    </script>
{% endblock %}

punch/templates/monitor/location_detail.html
{% extends "dash_base.html" %}
{% load staticfiles %}
{% block title %}{{ location.name }}{% endblock %}
{% block nav_title %}Overview{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Active tanks</h3>
      </div>
      <div class="panel-body">
      {% if active_tanks %}
        <ul>
        {% for tank in active_tanks %}
            <li><a href="{{ tank.get_absolute_url }}">{{ tank.name }}</a> <small>({{ tank.sensor_uuid }})</small></li>
        {% endfor %}
        </ul>
      {% else %}
          <p>There are currently no active batches being monitored.</p>

          <a href="{{ location.get_absolute_url }}tank/add" class="btn btn-medium btn-default">Add a new tank</a>
      {% endif %}
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Inactive tanks</h3>
      </div>
      <div class="panel-body">
      {% if finished_tanks %}
        <ul>
        {% for tank in finished_tanks %}
            <li><a href="{{ tank.get_absolute_url }}">{{ tank.name }}</a> <small>({{ tank.sensor_uuid }})</small></li>
        {% endfor %}
        </ul>
      {% else %}
          <p>You don't have any finished batches yet! Get cracking!</p>
      {% endif %}
      </div>
    </div>

    <br/><br/>
    <h5>Connected bridges to {{ location.name }}:</h5>
    <ul>
    {% for bridge in location.bridge_set.all %}
        <li>{{ bridge.uuid }}</li>
    {% endfor %}
    </ul>
    <a href="{{ location.get_absolute_url }}bridge/add" class="btn btn-xs btn-primary">Add another bridge</a>
{% endblock %}

punch/templates/monitor/location_form.html
{% extends "dash_base.html" %}
{% load staticfiles %}
{% block title %}Create a new location{% endblock %}
{% block nav_title %}Create location{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
    {% if location %}
        <h1>{{ location.name }}</h1>
    {% else %}
        <h1>We need a few details to setup your new location.</h1>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {% if location %}
            <button type="submit" class="btn btn-large btn-primary">Save</button>
        {% else %}
            <button type="submit" class="btn btn-large btn-primary">Create</button>
        {% endif %}
    </form>
{% endblock %}

punch/templates/monitor/tank_form.html
{% extends "dash_base.html" %}
{% load staticfiles %}
{% load addcss %}
{% block title %}Add a new tank{% endblock %}
{% block nav_title %}Add tank{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
    <nav>
      <ul class="pager">
        <li class="previous"><a href="{{ location.get_absolute_url }}"><span aria-hidden="true">&larr;</span> Back to location page</a></li>
      </ul>
    </nav>

    <h1>Let's set up a new tank for <span class="gray">{{ location.name }}</span></h1>
    <form method="POST">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="col-sm-7 alert alert-warning" role="alert">
              <span class="sr-only">Error:</span>
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <!-- Tank sensor UUID form -->
        <p class="lead">
            You'll need to choose from the list of available sensors. Make sure the UUID matches the device that
            you're putting in the tank.
        </p>
        {% if form.sensor_uuid.errors %}
        <div class="row">
            <div class="col-sm-7 alert alert-danger" role="alert">
              <span class="sr-only">Error:</span>
              {{ form.sensor_uuid.errors }}
            </div>
        </div>
        {% endif %}

        <div class="form-group">
            <div class="row">
            <label for="id_sensor_uuid" class="col-sm-1 control-label">Sensor UUID</label>
            <div class="col-sm-4">
                <select class="form-control" name="{{ form.sensor_uuid.name }}">
                  {% for s_uuid in sensor_uuids %}
                      <option>{{ s_uuid }}</option>
                  {% endfor %}
                </select>
            </div>
            </div>
        </div>

        <!-- Tank name form -->
        <p class="lead">Let's give your tank a <strong>descriptive</strong> name.</p>
        {% if form.name.errors %}
        <div class="row">
            <div class="col-sm-7 alert alert-danger" role="alert">
              <span class="sr-only">Error:</span>
              {{ form.name.errors }}
            </div>
        </div>
        {% endif %}

        <div class="form-group">
            <div class="row">
            <label for="id_name" class="col-sm-1 control-label">{{ form.name.label }}</label>
            <div class="col-sm-4">
                {{ form.name | addcss:"form-control"}}
            </div>
            </div>
        </div>
        <br/><br/>

        <!-- Tank Alerts temperature high form -->
        <div class="well well-lg">
            <p class="lead">Set when you want to be alerted <span class="gray">(optional)</span></p>
            {% if form.name.errors %}
            <div class="row">
                <div class="col-sm-7 alert alert-danger" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.alert_temp_high.errors }}
                  {{ form.alert_temp_low.errors }}
                </div>
            </div>
            {% endif %}
            <div class="form-group">
                <div class="row">
                    <label for="id_name" class="col-sm-4 control-label">{{ form.alert_temp_high.label }}</label>
                    <div class="col-sm-2">
                        {{ form.alert_temp_high | addcss:"form-control"}}
                    </div>
                    <div class="col-sm-1">°C</div>
                </div>
                <br/>
                <div class="row">
                    <label for="id_name" class="col-sm-4 control-label">{{ form.alert_temp_low.label }}</label>
                    <div class="col-sm-2">
                        {{ form.alert_temp_low | addcss:"form-control"}}
                    </div>
                    <div class="col-sm-1">°C</div>
                </div>
            </div>
        </div>

        <br/>
        <br/>
        <button type="submit" class="btn btn-large btn-primary">Add</button>
    </form>
{% endblock %}