punch/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

from punch.main import views as main_views
from punch.monitor import views as monitor_views


urlpatterns = patterns(
    '',
    # My URLS here
    url(r'^$', main_views.HomeView.as_view()),
    url(r'^signup$', main_views.RegisterView.as_view()),
    url(r'^login$', main_views.LoginView.as_view()),
    url(r'^logout$', main_views.LogoutView.as_view()),
    url(r'^dashboard$', main_views.DashboardView.as_view()),
    # Monitoring URLs
    url(r'^location/create$', monitor_views.LocationCreateView.as_view()),
    url(r'^location/(?P<pk>\d+)/$', monitor_views.LocationView.as_view(), name='location-detail'),
    url(r'^location/(?P<pk>\d+)/edit$', monitor_views.LocationEditView.as_view(), name='location-edit'),
    url(r'^location/(?P<l_pk>\d+)/bridge/add$', monitor_views.BridgeCreateView.as_view(), name='bridge-create'),
    url(r'^location/(?P<l_pk>\d+)/tank/add$', monitor_views.TankCreateView.as_view(), name='tank-create'),
    url(r'^location/(?P<l_pk>\d+)/tank/(?P<pk>\d+)/$', monitor_views.TankView.as_view(), name='tank-create'),
    url(r'^location/(?P<l_pk>\d+)/tank/(?P<pk>\d+)/end$', monitor_views.TankFinishRedirectView.as_view(), name='tank-finish'),
    # Update entry point
    url(r'^updater$', csrf_exempt(monitor_views.BridgeEntryView.as_view()), name='reading-entry-point'),
    url(r'^heartbeat$', csrf_exempt(monitor_views.HeartBeatEntryView.as_view()), name='heartbeat'),
    url(r'^admin/', include(admin.site.urls)),
)

punch/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


class UserProfile(models.Model):
    user = models.OneToOneField(User)

    # Validators
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )

    # Additional information
    phone_number = models.CharField(validators=[phone_regex], blank=True, max_length=17)

punch/monitor/models.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models


class Location(models.Model):
    """Model for describing a location which contains a bunch of sensors."""
    name = models.CharField(max_length=80)

    # For more details about many-to-many relationships in Django:
    # https://docs.djangoproject.com/en/dev/topics/db/examples/many_to_many/
    users = models.ManyToManyField(User)

    def get_absolute_url(self):
        return '/location/{id}/'.format(id=self.id)

    def __repr__(self):
        return '<Location: {name}>'.format(name=self.name)

    def __str__(self):
        return '<{name}>'.format(name=self.name)


class Bridge(models.Model):
    """Model that identifies a central hub."""
    # TODO: Figure out what this length should be
    uuid = models.CharField(max_length=32, unique=True)

    # For more details about many-to-one relationships in Django:
    # https://docs.djangoproject.com/en/1.7/topics/db/examples/many_to_one/
    location = models.ForeignKey(Location)

    def get_absolute_url(self):
        return self.location.get_absolute_url()


class Tank(models.Model):
    """Model that contains the fermentation tank abstraction."""
    # TODO: Figure out if this is the correct length for 128-bit hex identifier
    sensor_uuid = models.CharField(max_length=32)
    name = models.CharField(max_length=80)

    # Start/End date stuff
    # Automatically add the start date when the object is first created
    started_at = models.DateTimeField(auto_now_add=True)
    ended_at = models.DateTimeField(blank=True, null=True)

    # For UI Placement
    y = models.IntegerField(blank=True, null=True)
    x = models.IntegerField(blank=True, null=True)

    # Relationships
    location = models.ForeignKey(Location)

    # Alert settings
    alert_temp_high = models.FloatField(blank=True, null=True)
    alert_temp_low = models.FloatField(blank=True, null=True)
    alert_brix_high = models.FloatField(blank=True, null=True)
    alert_brix_low = models.FloatField(blank=True, null=True)

    @property
    def is_active(self):
        """Return a boolean indicating if the tank is currently active."""
        return self.ended_at is None

    def deactivate(self):
        """Deactivate this tank."""
        if self.is_active:
            self.ended_at = datetime.utcnow()

    @property
    def total_days(self):
        """Return the number of days that the tank was active for."""
        if self.is_active:
            dt = datetime.utcnow().replace(tzinfo=None) - self.started_at.replace(tzinfo=None)
        else:
            dt = self.ended_at.replace(tzinfo=None) - self.started_at.replace(tzinfo=None)
        return dt.days + 1

    def get_absolute_url(self):
        return self.location.get_absolute_url() + 'tank/{id}/'.format(id=self.id)


class Reading(models.Model):
    """Model that contains each readings for a particular tank."""
    # Relationships
    tank = models.ForeignKey(Tank)

    # Metrics
    temperature = models.FloatField()
    brix = models.FloatField()

    # Time of reading
    created_at = models.DateTimeField(auto_now_add=True)

punch/main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import EmailValidator

from punch.main.models import UserProfile


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': "A user with that username already exists.",
        'password_mismatch': "The two password fields didn't match.",
    }

    username = forms.CharField(label="Email address", max_length=30, validators=[EmailValidator])

    password1 = forms.CharField(label="Password",
        widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm password",
        widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification.")

    phone_number = forms.CharField(label="Phone number", max_length=17, validators=[UserProfile.phone_regex])

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        # The email and the username should be the same
        user.email = user.username

        # Force the save, disregard the commit flag
        user.save()

        # Hook it up to a user profile
        user_profile = UserProfile(user=user, phone_number=self.cleaned_data["phone_number"])
        user_profile.save()

        return user

punch/main/views.py
from django.views.generic import TemplateView, FormView, RedirectView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from punch.main.forms import UserCreationForm
from punch.mixins import LoginRequiredMixin


class HomeView(TemplateView):
    template_name = 'home.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class DashboardView(LoginRequiredMixin, RedirectView):
    template_name = 'dashboard.html'

    def get_redirect_url(self, *args, **kwargs):
        locations = self.request.user.location_set.all()
        if locations:
            return locations[0].get_absolute_url()
        else:
            return '/location/create'


class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = UserCreationForm
    success_url = '/dashboard'

    def form_valid(self, form):
        result = super(RegisterView, self).form_valid(form)

        # Login the user automatically after user is created
        user = authenticate(
            username=self.request.POST.get('username'),
            password=self.request.POST.get('password1')
        )
        login(self.request, user)

        return result


class LoginView(FormView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    success_url = '/dashboard'

    def form_valid(self, form):
        login(self.request, form.get_user())
        next_url = self.request.POST.get("next", self.success_url)
        return redirect(next_url)


class LogoutView(RedirectView):
    url = '/login'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

punch/monitor/views.py
import json
from datetime import datetime, timedelta
from random import random

from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import DetailView, RedirectView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from punch.monitor.lib.raw_bridge import RawBridge
from punch.monitor.models import (
    Location,
    Bridge,
    Tank,
    Reading,
)
from punch.monitor.forms import TankCreationForm, BridgeCreationForm
from punch.monitor.signals import check_and_send_alerts
from punch.mixins import LoginRequiredMixin


# TODO: permissions based on location ownership
# https://docs.djangoproject.com/en/1.7/topics/class-based-views/mixins/

# Good reference forms in general:
# https://docs.djangoproject.com/en/1.7/topics/class-based-views/generic-display/
# https://docs.djangoproject.com/en/1.7/topics/class-based-views/generic-editing/


class LocationCreateView(LoginRequiredMixin, CreateView):
    model = Location
    fields = ('name', 'users')


class LocationEditView(LoginRequiredMixin, UpdateView):
    model = Location


class LocationDeleteView(LoginRequiredMixin, DeleteView):
    model = Location


class LocationView(LoginRequiredMixin, DetailView):
    model = Location

    def get_context_data(self, **kwargs):
        context = super(LocationView, self).get_context_data(**kwargs)
        context['active_tanks'] = [tank for tank in self.object.tank_set.all() if tank.is_active]
        context['finished_tanks'] = [tank for tank in self.object.tank_set.all() if not tank.is_active]
        return context

    def dispatch(self, request, *args, **kwargs):
        location = get_object_or_404(Location, pk=kwargs['pk'])
        if location and not location.bridge_set.all():
            return redirect(location.get_absolute_url() + 'bridge/add')
        return super(LocationView, self).dispatch(request, *args, **kwargs)


class BridgeCreateView(LoginRequiredMixin, CreateView):
    model = Bridge
    fields = ('uuid', )
    form_class = BridgeCreationForm

    def get_context_data(self, **kwargs):
        context = super(BridgeCreateView, self).get_context_data(**kwargs)
        location = Location.objects.get(pk=int(self.kwargs.get('l_pk')))
        context['location'] = location
        context['needs_bridge'] = 1 - len(location.bridge_set.all())
        return context

    def form_valid(self, form):
        location = Location.objects.get(pk=self.kwargs.get('l_pk'))
        form.instance.location = location
        return super(BridgeCreateView, self).form_valid(form)


class BridgeDeleteView(LoginRequiredMixin, DeleteView):
    model = Bridge


class TankCreateView(LoginRequiredMixin, CreateView):
    model = Tank
    form_class = TankCreationForm
    fields = ('sensor_uuid', 'name')

    def get_context_data(self, **kwargs):
        context = super(TankCreateView, self).get_context_data(**kwargs)
        location = Location.objects.get(pk=int(self.kwargs.get('l_pk')))
        context['location'] = location
        context['sensor_uuids'] = self.get_sensor_uuids(location)
        return context

    def form_valid(self, form):
        location = Location.objects.get(pk=self.kwargs.get('l_pk'))
        form.instance.location = location
        self.remove_sensor_uuid(location, form.instance.sensor_uuid)
        return super(TankCreateView, self).form_valid(form)

    def get_sensor_uuids(self, location):
        sensor_uuids = []
        for bridge in location.bridge_set.all():
            b = RawBridge(bridge.uuid)
            sensor_uuids.extend(list(b.get_available_sensors()))
        return sensor_uuids

    def remove_sensor_uuid(self, location, sensor_uuid):
        for bridge in location.bridge_set.all():
            b = RawBridge(bridge.uuid)
            b.remove_available_sensor(sensor_uuid)


class TankEditView(LoginRequiredMixin, UpdateView):
    model = Tank


class TankDeleteView(LoginRequiredMixin, DeleteView):
    model = Tank


class TankView(LoginRequiredMixin, DetailView):
    model = Tank

    def get_context_data(self, **kwargs):
        context = super(TankView, self).get_context_data(**kwargs)
        location = Location.objects.get(pk=int(self.kwargs.get('l_pk')))
        context['location'] = location

        readings = self.object.reading_set.all()
        if readings:
            context['readings'] = serializers.serialize('json', readings)
        else:
            # If no readings, use randomly generated data
            context['readings'] = serializers.serialize('json', self.create_fake_readings())
        return context

    # TODO: remove when we have real readings
    def create_fake_readings(self):
        readings = []
        for i in range(0, 100):
            t = random() * 8 + 27
            b = random() * 2 + 30 - 1.02 ** i - i * 0.2
            d = datetime(2014, 11, 24, 18, 12, 8, 393455) + timedelta(minutes=120 * i)
            readings.append(Reading(temperature=t, brix=b, created_at=d))
        return readings


class TankFinishRedirectView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        tank = get_object_or_404(Tank, pk=kwargs['pk'])
        tank.deactivate()
        tank.save()
        return tank.get_absolute_url()


class BridgeEntryView(View):

    def post(self, request, *args, **kwargs):
        try:
            data = json.loads(request.body)
            self.process_load(data)
        except ValueError:
            pass
        return HttpResponse(
            json.dumps({'received': True}),
            content_type='application/json',
            **kwargs
        )

    def process_load(self, data):
        bridge_uuid = str(data['bridge_uuid'].replace('-', ''))
        sensor_uuid = str(data['sensor_uuid'])
        temperature = float(data['temperature'])
        brix = float(data['brix'])
        try:
            tank = Tank.objects.get(sensor_uuid=sensor_uuid, ended_at=None)
            # If tank exists, add a new reading
            reading = Reading(temperature=temperature, brix=brix, tank=tank)
            # TODO: add signal for reading
            reading.save()
            check_and_send_alerts(reading)
        except Tank.DoesNotExist:
            # Otherwise, tank doesn't exist and should be noticed by the set.
            r_bridge = RawBridge(bridge_uuid)
            r_bridge.add_available_sensor(sensor_uuid)


class HeartBeatEntryView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse(
            json.dumps({'received': True}),
            content_type='application/json',
            **kwargs
        )

punch/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title%}Punch{% endblock %} | Punch</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    {% block body %}
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static "assets/js/bootstrap.min.js" %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

punch/templates/dash_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title%}Punch{% endblock %} | Punch</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/dash.css" %}" rel="stylesheet">
    {% block css %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid container-wrap">
        <div class="navbar-header">
          <a class="navbar-brand" href="/dashboard">
            <img width="25px" alt="Brand" src="{% static "img/base/logo_square.png" %}">
          </a>
            <p class="navbar-text"><strong>{% block nav_title %}{% endblock %}</strong></p>

        </div>
       <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              {% if location %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ location.name }} <span class="caret"></span></a>
              {% else %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Locations <span class="caret"></span></a>
              {% endif %}
              <ul class="dropdown-menu" role="menu">
                {% if request.user.location_set.all %}
                    {% for loc in request.user.location_set.all %}
                        <li><a href="{{ loc.get_absolute_url }}">{{ loc.name }}</a></li>
                    {% endfor %}
                    <li class="divider"></li>
                {% endif %}
                <li><a href="/location/create">Add new location</a></li>
              </ul>
            </li>
            {% if location %}
                <li class="dropdown">
                  {% if tank %}
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ tank.name }} <span class="caret"></span></a>
                  {% else %}
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tanks <span class="caret"></span></a>
                  {% endif %}
                  <ul class="dropdown-menu" role="menu">
                    {% if location.tank_set.all %}
                        {% for tank in location.tank_set.all%}
                            {% if tank.is_active %}
                                <li><a href="{{ tank.get_absolute_url }}">{{ tank.name }}</a></li>
                            {% endif %}
                        {% endfor %}
                        <li class="divider"></li>
                    {% endif %}
                    <li><a href="{{ location.get_absolute_url }}tank/add">Add new tank</a></li>
                  </ul>
                </li>
            {% endif %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Settings <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="/settings">Profile Settings</a></li>
                <li><a href="/invite">Invite user</a></li>
                <li class="divider"></li>
                <li><a href="/logout">Logout</a></li>
              </ul>
            </li>
          </ul>
      </div>
    </nav>

    <div class="container-fluid container-wrap">
        {% block body %}
        {% endblock %}

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static "assets/js/bootstrap.min.js" %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

punch/templates/dashboard.html
{% extends "dash_base.html" %}
{% with nav_title="Dashboard" %}
{% load staticfiles %}

{% block title %}Dashboard{% endblock %}
{% block nav_title %}Dashboard{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
    <h1>hi</h1>
{% endblock %}

{% endwith %}

punch/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Welcome{% endblock %}

{% block css %}
    <link href="{% static "css/cover.css" %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">
          {% include "partials/nav.html" %}

          <div class="inner cover">
            <h1 class="cover-heading"><span class="purple">Punch</span> your wine.</h1>
            <p class="lead">Punch is a continuous Brix and temperature monitoring service for your fermenting wines. We'll aggregate the readings and send you realtime alerts when something's not quite right. Just drop it in a tank, and relax.</p>
            <p class="lead">
              <a href="/about" class="btn btn-lg btn-default">Learn more</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>A final project for <a href="http://husk.eecs.berkeley.edu/courses/cs294-84-fall14">Interactive Device Design</a>, by Team CAZM.</p>
            </div>
          </div>

        </div>

      </div>

    </div>
{% endblock %}

punch/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% load addcss %}
{% block title %}Login{% endblock %}

{% block css %}
    <link href="{% static "css/cover.css" %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="site-wrapper">
      <div class="site-wrapper-inner">

        <div class="cover-container">
          {% include "partials/nav.html" %}

          <div class="inner cover">
            <h3 class="cover-heading">Welcome back! Enter your credentials.</h3>
              <p>Don't have an account? <strong><a href="/signup">Register here.</a></strong></p>
            <br/>
            <form method="POST" class="form-horizontal" role="form">
                {% csrf_token %}
                {% if form.non_field_errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                    {{ form.non_field_errors }}
                </div>
                {% endif %}
                {% if form.username.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.username.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_username" class="col-sm-offset-2 col-sm-3 control-label">{{ form.username.label }}</label>
                    <div class="col-sm-4">
                        {{ form.username | addcss:"form-control"}}
                    </div>
                </div>
                {% if form.password.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.password.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_password" class="col-sm-offset-2 col-sm-3 control-label">{{ form.password.label }}</label>
                    <div class="col-sm-4">
                        {{ form.password | addcss:"form-control"}}
                    </div>
                </div>
                <br/>
                <button type="submit" class="btn btn-lg btn-default">Login</button>
            </form>

          </div>

        </div>

      </div>

    </div>

{% endblock %}

punch/templates/register.html
{% extends "base.html" %}
{% load staticfiles %}
{% load addcss %}
{% block title %}Register{% endblock %}

{% block css %}
    <link href="{% static "css/cover.css" %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="site-wrapper">
      <div class="site-wrapper-inner">

        <div class="cover-container">
          {% include "partials/nav.html" %}

          <div class="inner cover">
            <h3 class="cover-heading">Register now to start using Punch.</h3>
              <p>Already have an account? <strong><a href="/login">Login here.</a></strong></p>
            <br/>
            <form method="POST" class="form-horizontal" role="form">
                {% csrf_token %}
                {% if form.username.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.username.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_username" class="col-sm-offset-2 col-sm-3 control-label">{{ form.username.label }}</label>
                    <div class="col-sm-4">
                        {{ form.username | addcss:"form-control"}}
                    </div>
                </div>
                {% if form.first_name.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.first_name.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_first_name" class="col-sm-offset-2 col-sm-3 control-label">{{ form.first_name.label }}</label>
                    <div class="col-sm-4">
                        {{ form.first_name | addcss:"form-control"}}
                    </div>
                </div>
                {% if form.last_name.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.last_name.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_last_name" class="col-sm-offset-2 col-sm-3 control-label">{{ form.last_name.label }}</label>
                    <div class="col-sm-4">
                        {{ form.last_name | addcss:"form-control"}}
                    </div>
                </div>
                {% if form.phone_number.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.phone_number.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_phone_number" class="col-sm-offset-2 col-sm-3 control-label">{{ form.phone_number.label }}</label>
                    <div class="col-sm-4">
                        {{ form.phone_number | addcss:"form-control"}}
                    </div>
                </div>
                {% if form.password1.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.password1.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_password1" class="col-sm-offset-2 col-sm-3 control-label">{{ form.password1.label }}</label>
                    <div class="col-sm-4">
                        {{ form.password1 | addcss:"form-control"}}
                    </div>
                </div>
                {% if form.password2.errors %}
                <div class="col-sm-offset-2 col-sm-7 alert alert-warning" role="alert">
                  <span class="sr-only">Error:</span>
                  {{ form.password2.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_password2" class="col-sm-offset-2 col-sm-3 control-label">{{ form.password2.label }}</label>
                    <div class="col-sm-4">
                        {{ form.password2 | addcss:"form-control"}}
                    </div>
                </div>
                <br/>
                <button type="submit" class="btn btn-lg btn-default">Register</button>
            </form>
          </div>

        </div>

      </div>

    </div>

{% endblock %}